### ISSUE TITLE
Discoveries?

### ISSUE THREAD

**Issue by vincenzoromeo** [alexanderbcook/erowid-project#2]
Hi there,

This is a really interesting project. I'm wondering what spawned this idea, and what your discoveries have been so far.

Also, how would I bootstrap the project? I'm proficient in Python and could get hacking on this in no time (time permitting ofc!).

Cheers,
Vincent

**Comment by alexanderbcook** [comment]
Hi Vincent! 

I came across the Erowid experience vault a number of years ago and have always found the writing to be interesting and generally high quality. I've been interested in natural language parsing for some time and thought the experience vault would be a good dataset to play with. 

To bootstrap this project, you would need a PSQL database and an API key stored in a config.py at the root of the project. You can reach out to the Erowid team to receive an API key.

You can find writing that I've done about this project <a href=https://databyalex.com/erowid/sentiment> here</a> and <a href=https://databyalex.com/erowid/users> here</a>.
